repository_type: pipeline

nf_core_version: 3.1.1

lint:
  files_unchanged:
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-ASSEMBLY_ANALYSIS_PIPELINE_logo_light.png
    - docs/images/nf-core-ASSEMBLY_ANALYSIS_PIPELINE_logo_light.png
    - docs/images/nf-core-ASSEMBLY_ANALYSIS_PIPELINE_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CHANGELOG.md
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-ASSEMBLY_ANALYSIS_PIPELINE_logo_light.png
    - docs/images/nf-core-ASSEMBLY_ANALYSIS_PIPELINE_logo_light.png
    - docs/images/nf-core-ASSEMBLY_ANALYSIS_PIPELINE_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: ebi-metagenomics
  name: ASSEMBLY_ANALYSIS_PIPELINE
  description: MGnify's assembly analysis pipeline performs taxonomic classification,
    protein function prediction, and identifies metabolic pathways and biosynthetic
    gene clusters.
  author: mberacochea
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gitpod
    - fastqc
    - changelog
    - adaptivecard
    - slackreport
  is_nfcore: false
